### ISSUE TITLE
assumptions todo

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#34]
Make old and new systems consistent, see e.g. sympy/sympy#8134.  All old assumptions should be in the new system.
- [x] is_real vs Q.real & Q.extended_real (#36)
- [x] is_finite/is_infinite vs Q.bounded (#40, #41)
- [x] is_nonzero/Q.nonzero (#80)
- [x] ~~Float in the new assumptions, see sympy/sympy#9670~~

For old assumptions:
- [x] complex -> finite (#42)
- [x] manually check all assumption handlers (`_eval_is_*`): 1) be correct 2) be covered with tests. https://github.com/diofant/diofant/pull/316
     - [x] diofant/concrete/expr_with_limits.py
     - [x] diofant/concrete/products.py
     - [x] diofant/concrete/summations.py
     - [x] diofant/core/add.py
     - [x] diofant/core/expr.py
     - [x] diofant/core/function.py
     - [x] diofant/core/mod.py
     - [x] diofant/core/mul.py
     - [x] diofant/core/numbers.py
     - [x] diofant/core/power.py
     - [x] diofant/functions/combinatorial/factorials.py
     - [x] diofant/functions/combinatorial/numbers.py
     - [x] diofant/functions/elementary/complexes.py
     - [x] diofant/functions/elementary/exponential.py
     - [x] diofant/functions/elementary/hyperbolic.py
     - [x] diofant/functions/elementary/integers.py
     - [x] diofant/functions/elementary/piecewise.py
     - [x] diofant/functions/elementary/trigonometric.py
     - [x] diofant/functions/special/bessel.py
     - [x] diofant/functions/special/error_functions.py
     - [x] diofant/functions/special/gamma_functions.py
     - [x] diofant/integrals/integrals.py
     - [x] diofant/matrices/expressions/matadd.py
     - [x] diofant/matrices/expressions/matmul.py
     - [x] diofant/matrices/expressions/matpow.py
     - [x] diofant/ntheory/factor_.py
     - [x] diofant/polys/rootoftools.py
     - [x] diofant/series/order.py
     - [x] diofant/stats/rv.py
- [x] same for explicit assumption properties, e.g. `is_real = True`. #334
- [x] ~~Move old assumptions from Basic to Expr (https://github.com/sympy/sympy/issues/7214) #311~~
- [x] document all assumption properties in core/assumptions.py #331, #354 

(meta issue)

**Comment by skirpichev** [comment]
https://github.com/diofant/diofant/issues/849
https://github.com/diofant/diofant/pull/955

**Comment by skirpichev** [comment]
#959
