### ISSUE TITLE
Docs todo

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#65]
- [x] remove AUTHORS (no emails!), make mailmap_update.py working with aboutus.rst (https://github.com/skirpichev/omg/pull/87)
- [x] update png images (tutorial) https://github.com/skirpichev/omg/pull/159
- [x] ~~start FAQ from [this page](https://github.com/sympy/sympy/wiki/Faq)?~~
- [x] fix "Unknown section" warnings, see e.g. [this](https://readthedocs.org/builds/omg/2584903/) https://github.com/diofant/diofant/pull/299
- [ ] use [sphinxcontrib.spelling](http://sphinxcontrib-spelling.readthedocs.org/en/latest/) ? https://github.com/skirpichev/omg/pull/110
- [x] try to preserve signatures of decorated functions, see [this](http://stackoverflow.com/questions/147816/preserving-signatures-of-decorated-functions) or [this](https://numericalrecipes.wordpress.com/2009/05/25/signature-preserving-function-decorators/). https://github.com/skirpichev/omg/pull/95
- [x] ~~use [wrapt](http://wrapt.readthedocs.org/en/latest/index.html) instead of [decorator](http://pythonhosted.org/decorator/documentation.html) module?~~

(meta issue)
