### ISSUE TITLE
polys todo

### ISSUE THREAD

**Issue by skirpichev** [diofant/diofant#66]
- [x] foo.dom->foo.domain, remove duplicated prop, #308
- [x] use Fraction instead of PythonRational, #304
- [x] remove deprecated code, e.g. old_polynomialring.py, old_fractionfield.py (see sympy/sympy#1840, sympy/sympy#2126 and 8f04af5), see #402, #404 
- [x] fix existing \__repr__ methods (output should be suitable for eval), see #407 
- [x] address [this](https://github.com/sympy/sympy/issues/4697#issuecomment-36993571), esp.:
  - [x] `self` naming, https://github.com/diofant/diofant/pull/214
  - [x] ~~get__/set__ methods (to be properties)~~
- [x] sympy/sympy#10292, see #339
- [x] ~~integrate dispersion with polys, see https://github.com/sympy/sympy/pull/2679#issuecomment-32112790~~
- [x] drop xring (use "starred" unpacking in assignments), vring?, #403 
- [x] uneavluated RootOf, #400 
- [x] ~~missing docs from [this](https://mattpap.github.io/masters-thesis/html/index.html)?~~
- [x] ~~expand introductory docs, see sympy/sympy#11425?~~

(meta issue)
